[tool.isort]
profile = black
multi_line_output = 3
line_length = 88
include_trailing_comma = true

[tool.black]
line_length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = E203

[tool.bumpversion]
current_version = 1.0.0
commit = True
tag = True
sign_tags = True

[tool.bumpversion:file:app/_version.py]

[tool.bumpversion:file:CITATION.cff]

# [tool.bumpversion:file:Copyright.txt]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
    "integration",
]
markers = [
    "requires_gpu: mark a test that requires a GPU to run.",
    "slow: mark a test that takes a long time to run.",
]
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S